version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: investuser
      POSTGRES_PASSWORD: investpass
      POSTGRES_DB: mundoinvest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: